package com.example.johndeere

/*
Lista de categorías de lenguaje general, donde cata categoría tiene sus respectivas palabras.
 */

var GeneralCategoriesList = mutableListOf(
    Categories("Abecedario", mutableListOf(
        Words("A", R.raw.a),
        Words("B", R.raw.b),
        Words("C", R.raw.c),
        Words("D", R.raw.d),
        Words("E", R.raw.e),
        Words("F", R.raw.f),
        Words("G", R.raw.g),
        Words("H", R.raw.h),
        Words("I", R.raw.i),
        Words("J", R.raw.j),
        Words("K", R.raw.k),
        Words("L", R.raw.l),
        Words("Ll", R.raw.ll),
        Words("M", R.raw.m),
        Words("N", R.raw.n_),
        Words("Ñ", R.raw.enie),
        Words("O", R.raw.o),
        Words("P", R.raw.p),
        Words("Q", R.raw.q),
        Words("R", R.raw.r),
        Words("Rr", R.raw.rr),
        Words("S", R.raw.s),
        Words("T", R.raw.t),
        Words("U", R.raw.u),
        Words("V", R.raw.v),
        Words("W", R.raw.w),
        Words("X", R.raw.x),
        Words("Y", R.raw.y),
        Words("Z", R.raw.z)
    )
    ),
    Categories("Animales",mutableListOf(
        Words("Abeja", R.raw.abeja),
        Words("Águila", R.raw.aguila),
        Words("Araña", R.raw.arania),
        Words("Ardilla", R.raw.ardilla),
        Words("Burro", R.raw.burro),
        Words("Caballo", R.raw.caballo),
        Words("Cerdo", R.raw.cerdo),
        Words("Chango", R.raw.chango),
        Words("Conejo", R.raw.conejo),
        Words("Gato", R.raw.gato),
        Words("Gorila", R.raw.gorila),
        Words("Gusano", R.raw.gusano),
        Words("Jirafa", R.raw.jirafa),
        Words("León", R.raw.leon),
        Words("Mariposa", R.raw.mariposa),
        Words("Oso", R.raw.oso),
        Words("Pájaro", R.raw.pajaro),
        Words("Paloma", R.raw.paloma),
        Words("Pato",R.raw.pato),
        Words("Perro",R.raw.perro),
        Words("Pez", R.raw.pez),
        Words("Ratón", R.raw.raton),
        Words("Tigre", R.raw.tigre),
        Words("Toro", R.raw.toro),
        Words("Tortuga", R.raw.tortuga),
        Words("Vaca", R.raw.vaca),
        Words("Vívora", R.raw.vivora),
    )
    ),
    Categories("Colores",mutableListOf(
        Words("Amarillo",  R.raw.amarillo),
        Words("Azul", R.raw.azul),
        Words("Blanco", R.raw.blanco),
        Words("Café", R.raw.cafe),
        Words("Gris",  R.raw.gris),
        Words("Morado", R.raw.morado),
        Words("Naranja", R.raw.naranja),
        Words("Negro", R.raw.negro),
        Words("Oro",  R.raw.oro),
        Words("Plata", R.raw.plata),
        Words("Rojo", R.raw.rojo),
        Words("Rosa", R.raw.rosa),
        Words("Verde", R.raw.verde)
    )),
    Categories("Comida",mutableListOf(
        Words("Aceite", R.raw.aceite),
        Words("Agua", R.raw.agua),
        Words("Arroz", R.raw.arroz),
        Words("Azúcar",  R.raw.azucar),
        Words("Café", R.raw.cafe_bebida),
        Words("Caldo", R.raw.caldo),
        Words("Carne", R.raw.carne),
        Words("Cerveza", R.raw.cerveza),
        Words("Chile", R.raw.chile),
        Words("Chocolate", R.raw.chocolate),
        Words("Coca Cola", R.raw.cocacola),
        Words("Dulce",  R.raw.dulce),
        Words("Ensalada", R.raw.ensalada),
        Words("Frijol", R.raw.frijol),
        Words("Fruta", R.raw.fruta),
        Words("Galleta",  R.raw.galleta),
        Words("Hamburguesa", R.raw.hamburguesa),
        Words("Huevo", R.raw.huevo),
        Words("Leche", R.raw.leche),
        Words("Pan",  R.raw.pan),
        Words("Pastel", R.raw.pastel),
        Words("Pescado", R.raw.pescado),
        Words("Pizza", R.raw.pizza),
        Words("Pollo",  R.raw.pollo),
        Words("Queso", R.raw.queso),
        Words("Refresco", R.raw.refresco),
        Words("Sopa", R.raw.sopa),
        Words("Taco",  R.raw.taco),
        Words("Tortilla", R.raw.tortilla),
        Words("Verdura", R.raw.verdura)
    )),
    Categories("Cuerpo",mutableListOf(
        Words("Boca", R.raw.boca),
        Words("Cabeza", R.raw.cabeza),
        Words("Cara", R.raw.cara),
        Words("Cejas",  R.raw.cejas),
        Words("Corazón", R.raw.corazon),
        Words("Estómago", R.raw.estomago),
        Words("Hueso", R.raw.hueso),
        Words("Mano",  R.raw.mano),
        Words("Nariz", R.raw.nariz),
        Words("Ojos", R.raw.ojos),
        Words("Oreja", R.raw.oreja),
        Words("Pestañas", R.raw.pestanias),
        Words("Piel", R.raw.piel),
        Words("Pies", R.raw.pies),
        Words("Sangre", R.raw.sangre)
    )),
    Categories("Días de la Semana",mutableListOf(
        Words("Domingo", R.raw.domingo),
        Words("Lunes", R.raw.lunes),
        Words("Martes", R.raw.martes),
        Words("Miércoles",  R.raw.miercoles),
        Words("Jueves", R.raw.jueves),
        Words("Viernes", R.raw.viernes),
        Words("Sábado", R.raw.sabado)
    )),
    Categories("Frutas",mutableListOf(
        Words("Almendra", R.raw.almendra),
        Words("Cereza", R.raw.cereza),
        Words("Coco",R.raw.coco),
        Words("Durazno",  R.raw.durazno),
        Words("Fresa", R.raw.fresa),
        Words("Guayaba", R.raw.guayaba),
        Words("Jamaica", R.raw.jamaica),
        Words("Jícama",  R.raw.jicama),
        Words("Limón", R.raw.limon),
        Words("Mango", R.raw.mango),
        Words("Manzana", R.raw.manzana),
        Words("Melón",  R.raw.melon),
        Words("Naranja", R.raw.naranja_fruta),
        Words("Nuez", R.raw.nuez),
        Words("Papaya", R.raw.papaya),
        Words("Pera",  R.raw.pera),
        Words("Piña", R.raw.pinia),
        Words("Plátano", R.raw.platano),
        Words("Sandía", R.raw.sandia),
        Words("Tamarindo",  R.raw.tamarindo),
        Words("Toronja", R.raw.toronja),
        Words("Uva", R.raw.uva)
    )),
    Categories("Hogar",mutableListOf(
        Words("Baño", R.raw.banio),
        Words("Caja", R.raw.caja),
        Words("Cama", R.raw.cama),
        Words("Casa",  R.raw.casa),
        Words("Celular", R.raw.celular),
        Words("Cocina", R.raw.cocina),
        Words("Computadora", R.raw.computadora),
        Words("Cuarto",  R.raw.cuarto),
        Words("Cuchara", R.raw.cuchara),
        Words("Foco", R.raw.foco),
        Words("Gas", R.raw.gas),
        Words("Impresora", R.raw.impresora),
        Words("Lavadora", R.raw.lavadora),
        Words("Licuadora", R.raw.licuadora),
        Words("Llave", R.raw.llave),
        Words("Luz",  R.raw.luz),
        Words("Mesa", R.raw.mesa),
        Words("Plancha", R.raw.plancha),
        Words("Plato", R.raw.plato),
        Words("Puerta", R.raw.puerta),
        Words("Silla", R.raw.silla),
        Words("Teléfono", R.raw.telefono),
        Words("Tenedor", R.raw.tenedor),
        Words("Vaso",  R.raw.vaso),
        Words("Ventana", R.raw.ventana)
    )),
    Categories("Lugares",mutableListOf(
        Words("Antro", R.raw.antro),
        Words("Banco", R.raw.banco),
        Words("Calle", R.raw.calle),
        Words("Cantina",  R.raw.cantina),
        Words("Casa", R.raw.casa),
        Words("Centro", R.raw.centro),
        Words("Cine", R.raw.cine),
        Words("Ciudad", R.raw.ciudad),
        Words("Edificio", R.raw.edificio),
        Words("Escuela", R.raw.escuela),
        Words("Fábrica", R.raw.fabrica),
        Words("Feria", R.raw.feria),
        Words("Fiesta", R.raw.fiesta),
        Words("Hotel", R.raw.hotel),
        Words("Iglesia", R.raw.iglesia),
        Words("Mercado", R.raw.mercado),
        Words("Museo", R.raw.museo),
        Words("Restaurante", R.raw.restaurante),
        Words("Teatro", R.raw.teatro),
        Words("Tienda", R.raw.tienda)
    )),
    Categories("Meses del Año",mutableListOf(
        Words("Enero", R.raw.enero),
        Words("Febrero", R.raw.febrero),
        Words("Marzo", R.raw.marzo),
        Words("Abril", R.raw.abril),
        Words("Mayo", R.raw.mayo),
        Words("Junio", R.raw.junio),
        Words("Julio", R.raw.julio),
        Words("Agosto", R.raw.agosto),
        Words("Septiembre", R.raw.septiembre),
        Words("Octubre", R.raw.octubre),
        Words("Noviembre", R.raw.noviembre),
        Words("Diciembre", R.raw.diciembre)
    )),
    Categories("Números",mutableListOf(
        Words("Cero", R.raw.cero),
        Words("Uno", R.raw.uno),
        Words("Dos", R.raw.dos),
        Words("Tres", R.raw.tres),
        Words("Cuatro", R.raw.cuatro),
        Words("Cinco", R.raw.cinco),
        Words("Seis", R.raw.seis),
        Words("Siete", R.raw.siete),
        Words("Ocho", R.raw.ocho),
        Words("Nueve", R.raw.nueve),
        Words("Diez", R.raw.diez),
        Words("Once", R.raw.once),
        Words("Doce", R.raw.doce),
        Words("Trece", R.raw.trece),
        Words("Catorce", R.raw.catorce),
        Words("Quince", R.raw.quince),
        Words("Dieciseis", R.raw.dieciseis),
        Words("Diecisiete", R.raw.diecisiete),
        Words("Dieciocho", R.raw.dieciocho),
        Words("Diecinueve", R.raw.diecinueve),
        Words("Veinte", R.raw.veinte),
        Words("Veinticinco", R.raw.veinticinco),
        Words("Treinta", R.raw.treinta),
        Words("Cuarenta", R.raw.cuarenta),
        Words("Cincuenta", R.raw.cincuenta),
        Words("Sesenta", R.raw.sesenta),
        Words("Setenta", R.raw.setenta),
        Words("Ochenta", R.raw.ochenta),
        Words("Noventa", R.raw.noventa),
        Words("Cien", R.raw.cien),
        Words("Doscientos", R.raw.doscientos),
        Words("Trescientos", R.raw.trescientos),
        Words("Cuatrocientos", R.raw.cuatrocientos),
        Words("Quinientos", R.raw.quinientos),
        Words("Seiscientos", R.raw.seiscientos),
        Words("Setecientos", R.raw.setecientos),
        Words("Ochocientos", R.raw.ochocientos),
        Words("Novecientos", R.raw.novecientos),
        Words("Mil", R.raw.mil),
        Words("Un millón", R.raw.millon)
    )),
    Categories("Personas",mutableListOf(
        Words("Abuela", R.raw.abuela),
        Words("Abuelo", R.raw.abuelo),
        Words("Adulto", R.raw.adulto),
        Words("Amante", R.raw.amante),
        Words("Amiga", R.raw.amiga),
        Words("Amigo", R.raw.amigo),
        Words("Anciano", R.raw.anciano),
        Words("Bebé", R.raw.bebe),
        Words("Bisabuela", R.raw.bisabuela),
        Words("Bisabuelo", R.raw.bisabuelo),
        Words("Bisnieta", R.raw.bisnieta),
        Words("Bisnieto", R.raw.bisnieto),
        Words("Ciego", R.raw.ciego),
        Words("Compañero", R.raw.companiero),
        Words("Cuñada", R.raw.cuniada),
        Words("Cuñado", R.raw.cuniado),
        Words("Divorciado", R.raw.divorciado),
        Words("Esposa", R.raw.esposa),
        Words("Esposo", R.raw.esposo),
        Words("Hermana", R.raw.hermana),
        Words("Hermano", R.raw.hermano),
        Words("Hija", R.raw.hija),
        Words("hijastra", R.raw.hijastra),
        Words("hijastro", R.raw.hijastro),
        Words("Hijo", R.raw.hijo),
        Words("Hombre", R.raw.hombre),
        Words("Huérfano", R.raw.huerfano),
        Words("Madrastra", R.raw.madrastra),
        Words("Madrina", R.raw.madrina),
        Words("Mamá", R.raw.mama),
        Words("Matrimonio", R.raw.matrimonio),
        Words("Media hermana", R.raw.mediahermana),
        Words("Medio hermano", R.raw.mediohermano),
        Words("Mujer", R.raw.mujer),
        Words("Nieta", R.raw.nieta),
        Words("Nieto", R.raw.nieto),
        Words("Niña", R.raw.ninia),
        Words("Niño", R.raw.ninio),
        Words("Novia", R.raw.novia),
        Words("Novio", R.raw.novio),
        Words("Nuera", R.raw.nuera),
        Words("Oyente", R.raw.oyente),
        Words("Padrastro", R.raw.padrastro),
        Words("Padrino", R.raw.padrino),
        Words("Papá", R.raw.papa),
        Words("Pareja", R.raw.pareja),
        Words("Persona", R.raw.persona),
        Words("Prima", R.raw.prima),
        Words("Primo", R.raw.primo),
        Words("Señor", R.raw.senior),
        Words("Señora", R.raw.seniora),
        Words("Señorita", R.raw.seniorita),
        Words("Separado", R.raw.separado),
        Words("Sobrina", R.raw.sobrina),
        Words("Sobrino", R.raw.sobrino),
        Words("Soltero", R.raw.soltero),
        Words("Sordo", R.raw.sordo),
        Words("Suegra", R.raw.suegra),
        Words("Suegro", R.raw.suegro),
        Words("Tía", R.raw.tia),
        Words("Tío", R.raw.tio),
        Words("Unión libre", R.raw.unionlibre),
        Words("Vecino", R.raw.vecino),
        Words("Viudo", R.raw.viudo),
        Words("Yerno", R.raw.yerno)
    )),
    Categories("Preguntas",mutableListOf(
        Words("¿Cómo?", R.raw.como),
        Words("¿Cuál?", R.raw.cual),
        Words("¿Cuándo", R.raw.cuando),
        Words("¿Cuánto?", R.raw.cuanto),
        Words("¿Dónde?", R.raw.donde),
        Words("¿Para qué?", R.raw.paraque),
        Words("¿Por qué?", R.raw.porque),
        Words("¿Qué?", R.raw.que),
        Words("¿Quién?", R.raw.quien)
    )),
    Categories("Preposiciones, Adjetivos, Sustantivos, Adverbios",mutableListOf(
        Words("Abajo", R.raw.abajo),
        Words("Aburrido", R.raw.aburrido),
        Words("Accidente", R.raw.accidente),
        Words("Adentro", R.raw.adentro),
        Words("Afortunado", R.raw.afortunado),
        Words("Alegre / Divertido", R.raw.alegredivertido),
        Words("Algunos", R.raw.algunos),
        Words("Alto (estatura)", R.raw.alto_estatura),
        Words("Amable", R.raw.amable),
        Words("Antes", R.raw.antes),
        Words("Arriba", R.raw.arriba),
        Words("Asustado", R.raw.asustado),
        Words("Atención / Atento", R.raw.atencion_atento),
        Words("Baboso", R.raw.baboso),
        Words("Bonito", R.raw.bonito),
        Words("Broma", R.raw.broma),
        Words("Bueno", R.raw.bueno),
        Words("Cada", R.raw.cada),
        Words("Caliente", R.raw.caliente),
        Words("Cansado", R.raw.cansado),
        Words("Cariño", R.raw.carinio),
        Words("Celoso", R.raw.celoso),
        Words("Chaparro", R.raw.chaparro),
        Words("Chistoso", R.raw.chistoso),
        Words("Cobarde", R.raw.cobarde),
        Words("Contento", R.raw.contento),
        Words("Curioso", R.raw.curioso),
        Words("Débil", R.raw.debil),
        Words("Decente", R.raw.decente),
        Words("Delgado", R.raw.delgado),
        Words("Despacio", R.raw.despacio),
        Words("Diferente", R.raw.diferente),
        Words("Difícil", R.raw.dificil),
        Words("Diploma", R.raw.diploma),
        Words("Duda", R.raw.duda),
        Words("Egoísta", R.raw.egoista),
        Words("Ejemplo", R.raw.ejemplo),
        Words("Ejercicio", R.raw.ejercicio),
        Words("Enojado", R.raw.enojado),
        Words("Envidia", R.raw.envidia),
        Words("Especial", R.raw.especial),
        Words("Fácil", R.raw.facil),
        Words("Falso", R.raw.falso),
        Words("Feliz", R.raw.feliz),
        Words("Feo", R.raw.feo),
        Words("Flojo", R.raw.flojo),
        Words("Fuerte", R.raw.fuerte),
        Words("Fuerza", R.raw.fuerza),
        Words("Gordo", R.raw.gordo),
        Words("Gratis", R.raw.gratis),
        Words("Grosero", R.raw.grosero),
        Words("Guapo", R.raw.guapo),
        Words("Hambre", R.raw.hambre),
        Words("Historia", R.raw.historia),
        Words("Humilde", R.raw.humilde),
        Words("Importante", R.raw.importante),
        Words("Inteligente", R.raw.inteligente),
        Words("Jamás", R.raw.jamas),
        Words("Junta", R.raw.junta),
        Words("Junto", R.raw.junto),
        Words("Lejos", R.raw.lejos),
        Words("Libre", R.raw.libre),
        Words("Loco", R.raw.loco),
        Words("Lenguaje de Señas Mexicano", R.raw.lsm),
        Words("Malo", R.raw.malo),
        Words("Más", R.raw.mas),
        Words("Mejor", R.raw.mejor),
        Words("Miedo", R.raw.miedo),
        Words("Necio", R.raw.necio),
        Words("No", R.raw.no),
        Words("Nuevo", R.raw.nuevo),
        Words("Nunca", R.raw.nunca),
        Words("Ojalá", R.raw.ojala),
        Words("Paciencia", R.raw.paciencia),
        Words("Peor", R.raw.peor),
        Words("Pero", R.raw.pero),
        Words("Pobre", R.raw.pobre),
        Words("Presumido", R.raw.presumido),
        Words("Problema", R.raw.problema),
        Words("Rápido / Pronto", R.raw.rapidopronto),
        Words("Raro", R.raw.raro),
        Words("Secreto", R.raw.secreto),
        Words("Señas", R.raw.senias),
        Words("Sí", R.raw.si),
        Words("Sucio", R.raw.sucio),
        Words("Suerte", R.raw.suerte),
        Words("Todo", R.raw.todo),
        Words("Tonto", R.raw.tonto),
        Words("Travieso", R.raw.travieso),
        Words("Triste", R.raw.triste),
        Words("Verdad", R.raw.verdad),
        Words("Vergüenza", R.raw.verguenza),
    )),
    Categories("Pronombres",mutableListOf(
        Words("Él", R.raw.el),
        Words("Ella", R.raw.ella),
        Words("Ellos", R.raw.ellos),
        Words("Nosotros", R.raw.nosotros),
        Words("Tú", R.raw.tu),
        Words("Ustedes", R.raw.ustedes),
        Words("Yo", R.raw.yo)
    )),
    Categories("Puestos, Profesiones, Oficios",mutableListOf(
        Words("Abogado", R.raw.abogado),
        Words("Actor", R.raw.actor),
        Words("Albañil", R.raw.albanil),
        Words("Alumno", R.raw.alumno),
        Words("Arquitecto", R.raw.arquitecto),
        Words("Bombero", R.raw.bombero),
        Words("Carpintero", R.raw.carpintero),
        Words("Chofer", R.raw.chofer),
        Words("Dentista", R.raw.dentista),
        Words("Diputado", R.raw.diputado),
        Words("Director", R.raw.director),
        Words("Enfermera", R.raw.enfermera),
        Words("Gobernador", R.raw.gobernador),
        Words("Guardia", R.raw.guardia),
        Words("Ingeniero", R.raw.ingeniero),
        Words("Intérprete", R.raw.interprete),
        Words("Jefe", R.raw.jefe),
        Words("Licenciado", R.raw.licenciado),
        Words("Líder", R.raw.lider),
        Words("Maestro", R.raw.maestro),
        Words("Mecánico", R.raw.mecanico),
        Words("Médico", R.raw.medico),
        Words("Mesero", R.raw.mesero),
        Words("Policía", R.raw.policia),
        Words("Presidente", R.raw.presidente),
        Words("Profesor", R.raw.profesor),
        Words("Psicólogo", R.raw.psicologo),
        Words("Senador", R.raw.senador),
        Words("Soldado", R.raw.soldado),
        Words("Taxista", R.raw.taxista),
        Words("Técnico", R.raw.tecnico),
        Words("Vendedor", R.raw.vendedor)
    )),
    Categories("Ropa",mutableListOf(
        Words("Abrigo", R.raw.abrigo),
        Words("Brasier", R.raw.brasier),
        Words("Bufanda", R.raw.bufanda),
        Words("Calzón", R.raw.calzon),
        Words("Camisa", R.raw.camisa),
        Words("Corbata", R.raw.corbata),
        Words("Falda", R.raw.falda),
        Words("Medias", R.raw.medias),
        Words("Pantalón", R.raw.pantalon),
        Words("Tenis", R.raw.tenis),
        Words("Vestido", R.raw.vestido),
        Words("Zapatos", R.raw.zapatos)
    )),
    Categories("Saludos, Cortesías",mutableListOf(
        Words("Adiós", R.raw.adios),
        Words("Bien", R.raw.bien),
        Words("Buenas noches", R.raw.buenasnoches),
        Words("Buenas tardes", R.raw.buenastardes),
        Words("Buenos días", R.raw.buenosdias),
        Words("¿Cómo estás?", R.raw.comoestas),
        Words("¿Cómo te llamas?", R.raw.comotellamas),
        Words("De nada", R.raw.denada),
        Words("Gracias", R.raw.gracias),
        Words("Gusto de conocerte", R.raw.gustodeconocerte),
        Words("Hola", R.raw.hola),
        Words("Mal", R.raw.mal),
        Words("Más o menos", R.raw.masomenos),
        Words("Nos vemos", R.raw.nosvemos),
        Words("Perdón", R.raw.perdon),
        Words("Por favor", R.raw.porfavor)
    )),
    Categories("Tiempo",mutableListOf(
        Words("Ahora", R.raw.ahora),
        Words("Ahorita", R.raw.ahorita),
        Words("Aire", R.raw.aire),
        Words("Año", R.raw.anio),
        Words("Antier", R.raw.antier),
        Words("A veces", R.raw.aveces),
        Words("Ayer", R.raw.ayer),
        Words("Calendario", R.raw.calendario),
        Words("Calor", R.raw.calor),
        Words("Cumpleaños", R.raw.cumpleanios),
        Words("Después", R.raw.despues),
        Words("Día", R.raw.dia),
        Words("Edad", R.raw.edad),
        Words("Fecha", R.raw.fecha),
        Words("Frío", R.raw.frio),
        Words("Futuro", R.raw.futuro),
        Words("Hasta", R.raw.hasta),
        Words("Hora", R.raw.hora),
        Words("Hoy", R.raw.hoy),
        Words("invierno", R.raw.invierno),
        Words("Mañana", R.raw.maniana),
        Words("Medio día", R.raw.mediodia),
        Words("Mes", R.raw.mes),
        Words("Mientras", R.raw.mientras),
        Words("Minuto", R.raw.minuto),
        Words("Noche", R.raw.noche),
        Words("Otoño", R.raw.otonio),
        Words("Otra vez", R.raw.otravez),
        Words("Otro", R.raw.otro),
        Words("Pasado", R.raw.pasado),
        Words("Presente", R.raw.presente),
        Words("Primavera", R.raw.primavera),
        Words("Primera vez", R.raw.primeravez),
        Words("Próximo", R.raw.proximo),
        Words("Semana", R.raw.semana),
        Words("Siempre", R.raw.siempre),
        Words("Tarde", R.raw.tarde),
        Words("Temprano", R.raw.temprano),
        Words("Una vez", R.raw.unavez),
        Words("Verano", R.raw.verano),
        Words("Viento", R.raw.viento)
    )),
    Categories("Transporte",mutableListOf(
        Words("Avión", R.raw.avion),
        Words("Barco", R.raw.barco),
        Words("Bicicleta", R.raw.bicicleta),
        Words("Camión", R.raw.camion),
        Words("Carro", R.raw.carro),
        Words("Central de autobuses", R.raw.cdeautobuses),
        Words("Helocóptero", R.raw.helicoptero),
        Words("Metro", R.raw.metro),
        Words("Motocicleta", R.raw.motocicleta),
        Words("Taxi", R.raw.taxi),
        Words("Transporte", R.raw.transporte),
        Words("Tren", R.raw.tren)
    )),
    Categories("Verbos comunes",mutableListOf(
        Words("Aprender", R.raw.aprender),
        Words("Avisar", R.raw.avisar),
        Words("Ayudar", R.raw.ayudar),
        Words("Comer", R.raw.comer),
        Words("Comprar", R.raw.comprar),
        Words("Creer", R.raw.creer),
        Words("Cuidar", R.raw.cuidar),
        Words("Dar", R.raw.dar),
        Words("Decir", R.raw.decir),
        Words("Descansar", R.raw.descansar),
        Words("Dormir", R.raw.dormir),
        Words("Empezar", R.raw.empezar),
        Words("Enseñar", R.raw.enseniar),
        Words("Entender", R.raw.entender),
        Words("Escribir", R.raw.escribir),
        Words("Esperar", R.raw.esperar),
        Words("Estudiar", R.raw.estudiar),
        Words("Explicar", R.raw.explicar),
        Words("Hablar", R.raw.hablar),
        Words("Hacer", R.raw.hacer),
        Words("Jugar", R.raw.jugar),
        Words("Limpiar", R.raw.limpiar),
        Words("Necesitar", R.raw.necesitar),
        Words("Olvidar", R.raw.olvidar),
        Words("Pagar", R.raw.pagar),
        Words("Pensar", R.raw.pensar),
        Words("Perder", R.raw.perder),
        Words("Platicar", R.raw.platicar),
        Words("Poder", R.raw.poder),
        Words("Preguntar", R.raw.preguntar),
        Words("Sentar", R.raw.sentar),
        Words("Terminar", R.raw.terminar),
        Words("Trabajar", R.raw.trabajar),
        Words("Vender", R.raw.vender),
        Words("Ver", R.raw.ver),
        Words("Vivir", R.raw.vivir),
    )),
    Categories("Verbos narrativos",mutableListOf(
        Words("Conocer", R.raw.conocer),
        Words("Entender", R.raw.entendervn),
        Words("Gustar", R.raw.gustar),
        Words("Haber", R.raw.haber),
        Words("No conocer", R.raw.noconocer),
        Words("No entender", R.raw.noentender),
        Words("No gustar", R.raw.nogustar),
        Words("No haber", R.raw.nohaber),
        Words("No poder", R.raw.nopoder),
        Words("No querer", R.raw.noquerer),
        Words("No saber", R.raw.nosaber),
        Words("No servir", R.raw.noservir),
        Words("Poder", R.raw.podervn),
        Words("Querer", R.raw.querer),
        Words("Saber", R.raw.saber),
        Words("Servir", R.raw.servir)
    )),
    Categories("Verduras",mutableListOf(
        Words("Aguacate",R.raw.aguacate),
        Words("Ajo",R.raw.ajo),
        Words("Betabel",R.raw.betabel),
        Words("Calabacita",R.raw.calabacita),
        Words("Calabaza",R.raw.calabaza),
        Words("Camote",R.raw.camote),
        Words("Cebolla",R.raw.cebolla),
        Words("Chíchar",R.raw.chicharo),
        Words("Chile",R.raw.chile),
        Words("Elote",R.raw.elote),
        Words("Frijol",R.raw.frijol),
        Words("Hongo",R.raw.hongo),
        Words("Jitomate",R.raw.jitomate),
        Words("Lechuga",R.raw.lechuga),
        Words("Nopal",R.raw.nopal),
        Words("Papa",R.raw.papaverd),
        Words("Pepino",R.raw.pepino),
        Words("Zanahoria",R.raw.zanahoria),
    ))
)